[pytest]
;testpaths = pytest_automation/testing_with_pytest/tests

python_functions = test_* qual_*
;python_files =
;python_classes =

addopts = -rA --tb=short --html=report.html --emoji --strict-markers

xfail_strict = true

markers =
    func: functional cases
    reg: regression cases
    neg: negative cases
    file: file or directory related cases(e.g. tmp_path)
    cache: pytest cache related cases
    sys: test pytest capsys fixture for capturing system outputs and errors
    monkey: test pytest monkeypatch fixture
    warn: test pytest recwarn fixture or pytest.warns()
